services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    networks:
     - backend
    ports:
     - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d   
    environment:  
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sawyer
      - MYSQL_PASSWORD=root
     # TZ: Asia/Seoul

networks:
  backend: